/* automatically generated from wikipad-prefs-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (wikipad_prefs_dialog_ui)
#endif
#ifdef __GNUC__
static const char wikipad_prefs_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char wikipad_prefs_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"GtkListStore\" id=\"/prefs/edito"
  "r/smart-home-end-model\"><columns><column type=\"gint\"/><column type=\""
  "gchararray\"/></columns><data><row><col id=\"0\">0</col><col id=\"1\" t"
  "ranslatable=\"yes\">Disabled</col></row><row><col id=\"0\">1</col><col "
  "id=\"1\" translatable=\"yes\">Before</col></row><row><col id=\"0\">2</c"
  "ol><col id=\"1\" translatable=\"yes\">After</col></row><row><col id=\"0"
  "\">3</col><col id=\"1\" translatable=\"yes\">Always</col></row></data><"
  "/object><object class=\"GtkListStore\" id=\"/prefs/editor/tab-mode-stor"
  "e\"><columns><column type=\"gchararray\"/></columns><data><row><col id="
  "\"0\" translatable=\"yes\">Insert Tabs</col></row><row><col id=\"0\" tr"
  "anslatable=\"yes\">Insert Spaces</col></row></data></object><object cla"
  "ss=\"GtkAdjustment\" id=\"/prefs/editor/tab-width-adjustment\"><propert"
  "y name=\"lower\">1</property><property name=\"upper\">32</property><pro"
  "perty name=\"value\">8</property><property name=\"step_increment\">1</p"
  "roperty><property name=\"page_increment\">10</property></object><object"
  " class=\"GtkListStore\" id=\"/prefs/view/color-scheme-model\"><columns>"
  "<column type=\"gchararray\"/><column type=\"gchararray\"/></columns><da"
  "ta><row><col id=\"0\" translatable=\"yes\">none</col><col id=\"1\" tran"
  "slatable=\"yes\">None</col></row></data></object><object class=\"GtkAdj"
  "ustment\" id=\"/prefs/view/right-margin-adjustment\"><property name=\"u"
  "pper\">9999</property><property name=\"step_increment\">1</property><pr"
  "operty name=\"page_increment\">10</property></object><object class=\"Gt"
  "kListStore\" id=\"/prefs/window/toolbar/icon-size-model\"><columns><col"
  "umn type=\"GtkIconSize\"/><column type=\"gchararray\"/></columns><data>"
  "<row><col id=\"0\">menu</col><col id=\"1\" translatable=\"yes\">Menu</c"
  "ol></row><row><col id=\"0\">small-toolbar</col><col id=\"1\" translatab"
  "le=\"yes\">Small Toolbar</col></row><row><col id=\"0\">large-toolbar</c"
  "ol><col id=\"1\" translatable=\"yes\">Large Toolbar</col></row><row><co"
  "l id=\"0\">button</col><col id=\"1\" translatable=\"yes\">Button</col><"
  "/row><row><col id=\"0\">dnd</col><col id=\"1\" translatable=\"yes\">Dra"
  "g &amp; Drop</col></row><row><col id=\"0\">dialog</col><col id=\"1\" tr"
  "anslatable=\"yes\">Dialog</col></row></data></object><object class=\"Gt"
  "kListStore\" id=\"/prefs/window/toolbar/style-model\"><columns><column "
  "type=\"GtkToolbarStyle\"/><column type=\"gchararray\"/></columns><data>"
  "<row><col id=\"0\">icons</col><col id=\"1\" translatable=\"yes\">Icons "
  "Only</col></row><row><col id=\"0\">text</col><col id=\"1\" translatable"
  "=\"yes\">Text Only</col></row><row><col id=\"0\">both</col><col id=\"1\""
  " translatable=\"yes\">Text Below Icons</col></row><row><col id=\"0\">bo"
  "th-horiz</col><col id=\"1\" translatable=\"yes\">Text Beside Icons</col"
  "></row></data></object><object class=\"GtkNotebook\" id=\"/prefs/main-n"
  "otebook\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><child><object class=\"GtkVBox\" id=\"/prefs/v"
  "iew/content-area\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"border_width\">6</p"
  "roperty><child><object class=\"GtkFrame\" id=\"/prefs/view/display/fram"
  "e\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"label_xalign\">0</property><proper"
  "ty name=\"shadow_type\">none</property><child><object class=\"GtkAlignm"
  "ent\" id=\"/prefs/view/display/alignment\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"top_padding\">6</property><property name=\"bottom_padding\">6</pro"
  "perty><property name=\"left_padding\">12</property><property name=\"rig"
  "ht_padding\">6</property><child><object class=\"GtkVBox\" id=\"/prefs/v"
  "iew/display/content-area\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"spacing\">2"
  "</property><child><object class=\"GtkCheckButton\" id=\"/prefs/view/dis"
  "play/show-line-numbers-check\"><property name=\"label\" translatable=\""
  "yes\">Show line numbers</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"active\">True</property>"
  "<property name=\"draw_indicator\">True</property><signal name=\"toggled"
  "\" handler=\"on_show_line_numbers_toggled\" object=\"prefs_dialog\" swa"
  "pped=\"yes\"/></object><packing><property name=\"expand\">True</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkCheckButton\" id="
  "\"/prefs/view/display/display-whitespace-check\"><property name=\"label"
  "\" translatable=\"yes\">Display whitespace</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">False</property><property name=\"draw_"
  "indicator\">True</property></object><packing><property name=\"expand\">"
  "True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"/prefs/view/display/display-line-endings-check\"><proper"
  "ty name=\"label\" translatable=\"yes\">Display line endings</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">False</property><prop"
  "erty name=\"draw_indicator\">True</property></object><packing><property"
  " name=\"expand\">True</property><property name=\"fill\">True</property>"
  "<property name=\"position\">2</property></packing></child><child><objec"
  "t class=\"GtkHBox\" id=\"/prefs/view/display/long-line-margin-box\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"spacing\">6</property><child><object clas"
  "s=\"GtkCheckButton\" id=\"/prefs/view/display/long-line-check\"><proper"
  "ty name=\"label\" translatable=\"yes\">Long line margin at column:</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">False</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">0</property></packing></child><chil"
  "d><object class=\"GtkSpinButton\" id=\"/prefs/view/display/long-line-sp"
  "in\"><property name=\"visible\">True</property><property name=\"sensiti"
  "ve\">False</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"invisible_char\">\342\200\242</property><property name=\"inv"
  "isible_char_set\">True</property><property name=\"primary_icon_activata"
  "ble\">False</property><property name=\"secondary_icon_activatable\">Fal"
  "se</property><property name=\"primary_icon_sensitive\">True</property><"
  "property name=\"secondary_icon_sensitive\">True</property><property nam"
  "e=\"adjustment\">/prefs/view/right-margin-adjustment</property><propert"
  "y name=\"numeric\">True</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">True</property><property"
  " name=\"position\">1</property></packing></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">3</property></packing></child><child>"
  "<object class=\"GtkCheckButton\" id=\"/prefs/view/display/highlight-cur"
  "rent-line-check\"><property name=\"label\" translatable=\"yes\">Highlig"
  "ht current line</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">False</property><property name=\"active\">True</property><propert"
  "y name=\"draw_indicator\">True</property></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">4</property></packing></child><child><object c"
  "lass=\"GtkCheckButton\" id=\"/prefs/view/display/match-braces-check\"><"
  "property name=\"label\" translatable=\"yes\">Highlight matching bracket"
  "s</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"draw_indicator\">True</property></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">5</property></packing></child>"
  "<child><object class=\"GtkCheckButton\" id=\"/prefs/view/display/word-w"
  "rap-check\"><property name=\"label\" translatable=\"yes\">Wrap long lin"
  "es</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"draw_indicator\">True</property></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">6</property></packing></child>"
  "</object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"/prefs/view/display/label\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"label\" translatable=\"yes\">&lt;b&gt;Display&lt;/b&gt;</property"
  "><property name=\"use_markup\">True</property></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">0</property></packing><"
  "/child><child><object class=\"GtkFrame\" id=\"/prefs/view/font-frame\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label_xalign\">0</property><property n"
  "ame=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"/prefs/view/font/alignment\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"top"
  "_padding\">6</property><property name=\"bottom_padding\">6</property><p"
  "roperty name=\"left_padding\">12</property><property name=\"right_paddi"
  "ng\">6</property><child><object class=\"GtkVBox\" id=\"/prefs/view/font"
  "/box\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"spacing\">2</property><child><o"
  "bject class=\"GtkCheckButton\" id=\"/prefs/view/font/default-check\"><p"
  "roperty name=\"label\" translatable=\"yes\">Use system monospace font</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">False</prop"
  "erty><property name=\"draw_indicator\">True</property></object><packing"
  "><property name=\"expand\">True</property><property name=\"fill\">True<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkFontButton\" id=\"/prefs/view/font/chooser-butto"
  "n\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">True</property><"
  "/object><packing><property name=\"expand\">True</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">1</property></pac"
  "king></child></object></child></object></child><child type=\"label\"><o"
  "bject class=\"GtkLabel\" id=\"/prefs/view/font/label\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">&lt;b&gt;Font&lt;/b&gt;</p"
  "roperty><property name=\"use_markup\">True</property></object></child><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">True</property><property name=\"position\">1</property></pa"
  "cking></child><child><object class=\"GtkFrame\" id=\"/prefs/view/color-"
  "scheme-frame\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label_xalign\">0</prope"
  "rty><property name=\"shadow_type\">none</property><child><object class="
  "\"GtkAlignment\" id=\"/prefs/view/color-scheme-alignment\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"top_padding\">6</property><property name=\"bottom_"
  "padding\">6</property><property name=\"left_padding\">12</property><pro"
  "perty name=\"right_padding\">6</property><child><object class=\"GtkVBox"
  "\" id=\"/prefs/view/color-scheme-box\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "spacing\">2</property><child><object class=\"GtkComboBox\" id=\"/prefs/"
  "view/color-scheme-combo\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"model\">/pre"
  "fs/view/color-scheme-model</property><property name=\"active\">0</prope"
  "rty><child><object class=\"GtkCellRendererText\" id=\"/prefs/view/color"
  "-scheme-cell-renderer\"/><attributes><attribute name=\"text\">1</attrib"
  "ute></attributes></child></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">0</property></packing></child></object></child></object></chil"
  "d><child type=\"label\"><object class=\"GtkLabel\" id=\"/prefs/view/col"
  "or-scheme-label\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"label\" translatable"
  "=\"yes\">&lt;b&gt;Colour scheme&lt;/b&gt;</property><property name=\"us"
  "e_markup\">True</property></object></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"position\">2</property></packing></child></object></ch"
  "ild><child type=\"tab\"><object class=\"GtkLabel\" id=\"/prefs/view/tab"
  "-label\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "View</property></object><packing><property name=\"tab_fill\">False</pro"
  "perty></packing></child><child><object class=\"GtkVBox\" id=\"/prefs/ed"
  "itor/content-area\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"border_width\">6</"
  "property><property name=\"spacing\">6</property><child><object class=\""
  "GtkFrame\" id=\"/prefs/editor/indentation/frame\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label_xalign\">0</property><property name=\"shadow_type\">n"
  "one</property><child><object class=\"GtkAlignment\" id=\"/prefs/editor/"
  "indentation/alignment\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"top_padding\">"
  "6</property><property name=\"bottom_padding\">6</property><property nam"
  "e=\"left_padding\">12</property><property name=\"right_padding\">6</pro"
  "perty><child><object class=\"GtkTable\" id=\"/prefs/editor/indentation/"
  "table\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"n_rows\">3</property><property"
  " name=\"n_columns\">2</property><property name=\"column_spacing\">6</pr"
  "operty><property name=\"row_spacing\">6</property><child><object class="
  "\"GtkLabel\" id=\"/prefs/editor/indentation/tab-width-label\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"xalign\">0</property><property name=\"label\" t"
  "ranslatable=\"yes\">Tab width:</property></object><packing><property na"
  "me=\"x_options\">GTK_FILL</property><property name=\"y_options\">GTK_FI"
  "LL</property></packing></child><child><object class=\"GtkLabel\" id=\"/"
  "prefs/editor/indentation/tab-mode-label\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"xalign\">0</property><property name=\"label\" translatable=\"yes\">"
  "Tab mode:</property></object><packing><property name=\"top_attach\">1</"
  "property><property name=\"bottom_attach\">2</property><property name=\""
  "x_options\">GTK_FILL</property><property name=\"y_options\">GTK_FILL</p"
  "roperty></packing></child><child><object class=\"GtkSpinButton\" id=\"/"
  "prefs/editor/tab-width-spin\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"invisible"
  "_char\">\342\200\242</property><property name=\"invisible_char_set\">Tr"
  "ue</property><property name=\"primary_icon_activatable\">False</propert"
  "y><property name=\"secondary_icon_activatable\">False</property><proper"
  "ty name=\"primary_icon_sensitive\">True</property><property name=\"seco"
  "ndary_icon_sensitive\">True</property><property name=\"adjustment\">/pr"
  "efs/editor/tab-width-adjustment</property></object><packing><property n"
  "ame=\"left_attach\">1</property><property name=\"right_attach\">2</prop"
  "erty><property name=\"y_options\">GTK_FILL</property></packing></child>"
  "<child><object class=\"GtkComboBox\" id=\"/prefs/editor/tab-mode-combo\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"model\">/prefs/editor/tab-mode-store<"
  "/property><property name=\"active\">0</property><child><object class=\""
  "GtkCellRendererText\" id=\"editor.tab_mode.cellrenderer\"/><attributes>"
  "<attribute name=\"text\">0</attribute></attributes></child></object><pa"
  "cking><property name=\"left_attach\">1</property><property name=\"right"
  "_attach\">2</property><property name=\"top_attach\">1</property><proper"
  "ty name=\"bottom_attach\">2</property><property name=\"x_options\">GTK_"
  "FILL</property><property name=\"y_options\">GTK_FILL</property></packin"
  "g></child><child><object class=\"GtkCheckButton\" id=\"/prefs/editor/au"
  "to-indent-check\"><property name=\"label\" translatable=\"yes\">Enable "
  "automatic indentation</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">False</property><property name=\"draw_indicator\">True</pro"
  "perty></object><packing><property name=\"right_attach\">2</property><pr"
  "operty name=\"top_attach\">2</property><property name=\"bottom_attach\""
  ">3</property><property name=\"x_options\">GTK_FILL</property><property "
  "name=\"y_options\">GTK_FILL</property></packing></child></object></chil"
  "d></object></child><child type=\"label\"><object class=\"GtkLabel\" id="
  "\"/prefs/editor/indentation/label\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">&lt;b&gt;Indentation&lt;/b&gt;</property><pr"
  "operty name=\"use_markup\">True</property></object></child></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkFrame\" id=\"/prefs/editor/home-end/frame\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label_xalign\">0</property><property "
  "name=\"shadow_type\">none</property><child><object class=\"GtkAlignment"
  "\" id=\"/prefs/editor/home-end/alignment\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"top_padding\">6</property><property name=\"bottom_padding\">6</pro"
  "perty><property name=\"left_padding\">12</property><property name=\"rig"
  "ht_padding\">6</property><child><object class=\"GtkHBox\" id=\"/prefs/e"
  "ditor/home-end/box\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"spacing\">6</prop"
  "erty><child><object class=\"GtkLabel\" id=\"/prefs/editor/home-end/beha"
  "viour-label\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"xalign\">0</property><pr"
  "operty name=\"label\" translatable=\"yes\">Behaviour:</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"position\">0</property></packing>"
  "</child><child><object class=\"GtkComboBox\" id=\"/prefs/editor/smart-h"
  "ome-end-combo\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"model\">/prefs/editor/"
  "smart-home-end-model</property><property name=\"active\">0</property><c"
  "hild><object class=\"GtkCellRendererText\" id=\"/prefs/editor/smart-hom"
  "e-end-cellrenderer\"/><attributes><attribute name=\"text\">1</attribute"
  "></attributes></child></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child></object></child></object></child><"
  "child type=\"label\"><object class=\"GtkLabel\" id=\"/prefs/editor/home"
  "-end/label\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">&lt;b&gt;Home/End Keys&lt;/b&gt;</property><property name=\"use_mark"
  "up\">True</property></object></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">True</property><proper"
  "ty name=\"position\">1</property></packing></child></object><packing><p"
  "roperty name=\"position\">1</property></packing></child><child type=\"t"
  "ab\"><object class=\"GtkLabel\" id=\"/prefs/editor/tab-label\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label\" translatable=\"yes\">Editor</property>"
  "</object><packing><property name=\"position\">1</property><property nam"
  "e=\"tab_fill\">False</property></packing></child><child><object class=\""
  "GtkVBox\" id=\"/prefs/window/content-area\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"border_width\">6</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkFrame\" id=\"/prefs/window/general/frame\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label_xalign\">0</property><property na"
  "me=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"/prefs/window/general/alignment\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"top_padding\">6</property><property name=\"bottom_padding\">6</proper"
  "ty><property name=\"left_padding\">12</property><property name=\"right_"
  "padding\">6</property><child><object class=\"GtkVBox\" id=\"/prefs/wind"
  "ow/general/box\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"spacing\">2</property"
  "><child><object class=\"GtkCheckButton\" id=\"/prefs/window/general/sho"
  "w-statusbar-check\"><property name=\"label\" translatable=\"yes\">Show "
  "status bar</property><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"draw_indicator\">True</property></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkCheckButton\" id=\"/prefs/window/gen"
  "eral/show-path-in-title-check\"><property name=\"label\" translatable=\""
  "yes\">Show full filename in title bar</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">False</property><property name=\"draw_indic"
  "ator\">True</property></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkCheckButt"
  "on\" id=\"/prefs/window/general/remember-window-size-check\"><property "
  "name=\"label\" translatable=\"yes\">Remember window size</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">False</property><propert"
  "y name=\"draw_indicator\">True</property></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">2</property></packing></child><child><object c"
  "lass=\"GtkCheckButton\" id=\"/prefs/window/general/remember-window-posi"
  "tion-check\"><property name=\"label\" translatable=\"yes\">Remember win"
  "dow position</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"draw_indicator\">True</property></o"
  "bject><packing><property name=\"expand\">True</property><property name="
  "\"fill\">True</property><property name=\"position\">3</property></packi"
  "ng></child><child><object class=\"GtkCheckButton\" id=\"/prefs/window/g"
  "eneral/remember-window-state-check\"><property name=\"label\" translata"
  "ble=\"yes\">Remember window state</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><property na"
  "me=\"receives_default\">False</property><property name=\"draw_indicator"
  "\">True</property></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">4</property></packing></child></object></child></object></child><child"
  " type=\"label\"><object class=\"GtkLabel\" id=\"/prefs/window/general/l"
  "abel\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"yes\">&l"
  "t;b&gt;General&lt;/b&gt;</property><property name=\"use_markup\">True</"
  "property></object></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkFram"
  "e\" id=\"/prefs/window/toolbar/frame\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"/prefs/window/toolbar/alig"
  "nment1\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"top_padding\">6</property><pr"
  "operty name=\"bottom_padding\">6</property><property name=\"left_paddin"
  "g\">12</property><property name=\"right_padding\">6</property><child><o"
  "bject class=\"GtkTable\" id=\"/prefs/window/toolbar/table\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"n_rows\">3</property><property name=\"n_columns\""
  ">2</property><property name=\"column_spacing\">6</property><property na"
  "me=\"row_spacing\">6</property><child><object class=\"GtkCheckButton\" "
  "id=\"/prefs/window/toolbar/visible-check\"><property name=\"label\" tra"
  "nslatable=\"yes\">Show toolbar</property><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">True</property><property name="
  "\"receives_default\">False</property><property name=\"draw_indicator\">"
  "True</property></object><packing><property name=\"right_attach\">2</pro"
  "perty></packing></child><child><object class=\"GtkLabel\" id=\"/prefs/w"
  "indow/toolbar/style-label\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"xalign\">0"
  "</property><property name=\"label\" translatable=\"yes\">Style:</proper"
  "ty></object><packing><property name=\"top_attach\">1</property><propert"
  "y name=\"bottom_attach\">2</property><property name=\"x_options\">GTK_F"
  "ILL</property><property name=\"y_options\">GTK_FILL</property></packing"
  "></child><child><object class=\"GtkLabel\" id=\"/prefs/window/toolbar/i"
  "con-size-label\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"xalign\">0</property>"
  "<property name=\"label\" translatable=\"yes\">Icon Size:</property></ob"
  "ject><packing><property name=\"top_attach\">2</property><property name="
  "\"bottom_attach\">3</property><property name=\"x_options\">GTK_FILL</pr"
  "operty><property name=\"y_options\">GTK_FILL</property></packing></chil"
  "d><child><object class=\"GtkComboBox\" id=\"/prefs/window/toolbar/style"
  "-combo\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"model\">/prefs/window/toolbar"
  "/style-model</property><property name=\"active\">0</property><child><ob"
  "ject class=\"GtkCellRendererText\" id=\"/prefs/window/toolbar/style/cel"
  "lrenderer\"/><attributes><attribute name=\"text\">1</attribute></attrib"
  "utes></child></object><packing><property name=\"left_attach\">1</proper"
  "ty><property name=\"right_attach\">2</property><property name=\"top_att"
  "ach\">1</property><property name=\"bottom_attach\">2</property></packin"
  "g></child><child><object class=\"GtkComboBox\" id=\"/prefs/window/toolb"
  "ar/icon-size-combo\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"model\">/prefs/wi"
  "ndow/toolbar/icon-size-model</property><property name=\"active\">0</pro"
  "perty><child><object class=\"GtkCellRendererText\" id=\"/prefs/window/t"
  "oolbar/icon-size/cellrenderer1\"/><attributes><attribute name=\"text\">"
  "1</attribute></attributes></child></object><packing><property name=\"le"
  "ft_attach\">1</property><property name=\"right_attach\">2</property><pr"
  "operty name=\"top_attach\">2</property><property name=\"bottom_attach\""
  ">3</property></packing></child></object></child></object></child><child"
  " type=\"label\"><object class=\"GtkLabel\" id=\"/prefs/window/toolbar/l"
  "abel1\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label\" translatable=\"yes\">&"
  "lt;b&gt;Toolbar&lt;/b&gt;</property><property name=\"use_markup\">True<"
  "/property></object></child></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkFram"
  "e\" id=\"/prefs/window/notebook/frame\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label_xalign\">0</property><property name=\"shadow_type\">none</prope"
  "rty><child><object class=\"GtkAlignment\" id=\"/prefs/window/notebook/a"
  "lignment\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"top_padding\">6</property><"
  "property name=\"bottom_padding\">6</property><property name=\"left_padd"
  "ing\">12</property><property name=\"right_padding\">6</property><child>"
  "<object class=\"GtkVBox\" id=\"/prefs/window/notebook/box\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"spacing\">2</property><child><object class=\"GtkC"
  "heckButton\" id=\"/prefs/window/notebook/always-show-tabs-check\"><prop"
  "erty name=\"label\" translatable=\"yes\">Always show tabs even with one"
  " file</property><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"receives_default\">Fals"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkCheckButton\" id=\"/prefs/window/notebook/"
  "cycle-tabs-check\"><property name=\"label\" translatable=\"yes\">Cycled"
  " notebook tab switching</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"yalign\">0.5500000119209"
  "2896</property><property name=\"draw_indicator\">True</property></objec"
  "t><packing><property name=\"expand\">True</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">1</property></packing><"
  "/child></object></child></object></child><child type=\"label\"><object "
  "class=\"GtkLabel\" id=\"/prefs/window/notebook/label\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">&lt;b&gt;Notebook tabs&lt;"
  "/b&gt;</property><property name=\"use_markup\">True</property></object>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">2</prop"
  "erty></packing></child></object><packing><property name=\"position\">2<"
  "/property></packing></child><child type=\"tab\"><object class=\"GtkLabe"
  "l\" id=\"/prefs/window/tab-label\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">Window</property></object><packing><property "
  "name=\"position\">2</property><property name=\"tab_fill\">False</proper"
  "ty></packing></child></object></interface>"
};

static const unsigned wikipad_prefs_dialog_ui_length = 30802u;

