/* automatically generated from wikipad-window-ui.xml */
#ifdef __SUNPRO_C
#pragma align 4 (wikipad_window_ui)
#endif
#ifdef __GNUC__
static const char wikipad_window_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char wikipad_window_ui[] =
#endif
{
  "<ui><menubar name=\"main-menu\"><menu action=\"file-menu\"><menuitem ac"
  "tion=\"new\" /><menuitem action=\"new-window\" /><menuitem action=\"tem"
  "plate-menu\" /><separator /><menuitem action=\"open\" /><menu action=\""
  "recent-menu\"><menuitem action=\"no-recent-items\" /><placeholder name="
  "\"placeholder-recent-items\" /><separator /><menuitem action=\"clear-re"
  "cent\" /></menu><separator /><menuitem action=\"save\" /><menuitem acti"
  "on=\"save-as\" /><menuitem action=\"save-all\" /><menuitem action=\"rev"
  "ert\" /><separator /><menuitem action=\"print\" /><separator /><menuite"
  "m action=\"detach\" /><separator /><menuitem action=\"close\" /><menuit"
  "em action=\"close-window\" /></menu><menu action=\"edit-menu\"><menuite"
  "m action=\"undo\" /><menuitem action=\"redo\" /><separator /><menuitem "
  "action=\"cut\" /><menuitem action=\"copy\" /><menuitem action=\"paste\""
  " /><menu action=\"paste-menu\"><menuitem action=\"paste-history\" /><me"
  "nuitem action=\"paste-column\" /></menu><menuitem action=\"delete\" /><"
  "separator /><menuitem action=\"select-all\" /><menuitem action=\"change"
  "-selection\" /><separator /><menu action=\"move-menu\"><menuitem action"
  "=\"line-up\" /><menuitem action=\"line-down\" /></menu><menuitem action"
  "=\"duplicate\" /><menuitem action=\"increase-indent\" /><menuitem actio"
  "n=\"decrease-indent\" /><separator /><menuitem action=\"preferences\" /"
  "></menu><menu action=\"search-menu\"><menuitem action=\"find\" /><menui"
  "tem action=\"find-next\" /><menuitem action=\"find-previous\" /><menuit"
  "em action=\"replace\" /><separator /><menuitem action=\"go-to\" /></men"
  "u><menu action=\"view-menu\"><menuitem action=\"font\" /><separator /><"
  "menu action=\"color-scheme-menu\"><placeholder name=\"placeholder-color"
  "-scheme-items\" /></menu><menuitem action=\"line-numbers\" /><separator"
  " /><menuitem action=\"menubar\" /><menuitem action=\"toolbar\" /><menui"
  "tem action=\"statusbar\" /><separator /><menuitem action=\"fullscreen\""
  " /></menu><menu action=\"document-menu\"><menuitem action=\"auto-indent"
  "\" /><menu action=\"eol-menu\"><menuitem action=\"unix\" /><menuitem ac"
  "tion=\"mac\" /><menuitem action=\"dos\" /></menu><menu action=\"tab-siz"
  "e-menu\"><placeholder name=\"placeholder-tab-items\" /><separator /><me"
  "nuitem action=\"insert-spaces\" /></menu><menuitem action=\"word-wrap\""
  " /><separator /><menuitem action=\"write-bom\" /><separator /><menuitem"
  " action=\"back\" /><menuitem action=\"forward\" /><separator /><placeho"
  "lder name=\"placeholder-file-items\" /></menu><menu action=\"help-menu\""
  "><menuitem action=\"contents\" /><menuitem action=\"about\" /></menu></"
  "menubar><toolbar action=\"main-toolbar\"><toolitem action=\"new\" /><to"
  "olitem action=\"open\" /><toolitem action=\"save\" /><toolitem action=\""
  "save-as\" /><toolitem action=\"revert\" /><toolitem action=\"close\" />"
  "<separator /><toolitem action=\"undo\" /><toolitem action=\"redo\" /><t"
  "oolitem action=\"cut\" /><toolitem action=\"copy\" /><toolitem action=\""
  "paste\" /><separator /><toolitem action=\"find\" /><toolitem action=\"r"
  "eplace\" /><toolitem action=\"go-to\" /><separator name=\"spacer\" /><t"
  "oolitem action=\"fullscreen\" /></toolbar><popup action=\"tab-menu\"><m"
  "enuitem action=\"save\" /><menuitem action=\"save-as\" /><separator /><"
  "menuitem action=\"revert\" /><separator /><menuitem action=\"detach\" /"
  "><menuitem action=\"close\" /></popup><popup action=\"textview-menu\"><"
  "menuitem action=\"undo\" /><menuitem action=\"redo\" /><separator /><me"
  "nuitem action=\"cut\" /><menuitem action=\"copy\" /><menuitem action=\""
  "paste\" /><menu action=\"paste-menu\"><menuitem action=\"paste-history\""
  " /><menuitem action=\"paste-column\" /></menu><menuitem action=\"delete"
  "\" /><separator /><menuitem action=\"select-all\" /><menuitem action=\""
  "change-selection\" /><separator /><menu action=\"convert-menu\"><menuit"
  "em action=\"lowercase\" /><menuitem action=\"uppercase\" /><menuitem ac"
  "tion=\"titlecase\" /><menuitem action=\"opposite-case\" /><separator />"
  "<menuitem action=\"tabs-to-spaces\" /><menuitem action=\"spaces-to-tabs"
  "\" /><separator /><menuitem action=\"strip-trailing\" /><separator /><m"
  "enuitem action=\"transpose\" /></menu><menu action=\"move-menu\"><menui"
  "tem action=\"line-up\" /><menuitem action=\"line-down\" /></menu><menui"
  "tem action=\"duplicate\" /><menuitem action=\"increase-indent\" /><menu"
  "item action=\"decrease-indent\" /><separator name=\"menubar-visible-sep"
  "arator\" /><menuitem name=\"menubar-visible-item\" action=\"menubar\" /"
  "></popup></ui>"
};

static const unsigned wikipad_window_ui_length = 4176u;

